add_newline = false

format = """
[\\[](bright-black)[$time](bright-black)[\\]](bright-black) [$username](yellow)[@](green)[$hostname](blue) [$directory](purple)
$character
"""

[time]
disabled = false
format = "$time"
time_format = "%H:%M" 

[username]
show_always = true
format = "$user"

[hostname]
ssh_only = false
format = "$hostname"
style = "blue"

[directory]
format = "$path"
truncation_length = 100
truncate_to_repo = false
style = "cyan"

[character]
success_symbol = "[\\[](bright-black)[>](bright-black)[\\]](bright-black)"
error_symbol = "[\\[](red)[>](red)[\\]](red)"
