version = "1.1.15"

[class]
DEFAULT = "{class}"
"Anki" = " "
"blueman-manager-wrapped" = " "
"chromium" = " "
"com.obsproject.Studio" = "󰄄 "
"com.usebottles.bottles" = " "
"discord" = "󰊴 "
"Element" = " "
"emacs" = " "
"firefox" = " "
"foot" = " "
"ghidra" = " "
"Gimp" = " "
"Alacritty" = " "
"libreoffice-calc" = " "
"libreoffice-draw" = "󰽉 "
"libreoffice-impress" = "󰈩 "
"libreoffice-writer" = "󰷈 "
"mpv" = " "
"mullvad vpn" = " "
"Nsxiv" = " "
"org.getmonero." = " "
"org.kde.kdenlive" = " "
"signal" = "󰭹 "
"Slack" = "󰒱 "
"spotify" = " "
"st-256color" = " "
"steam" = " "
"teams-for-linux" = "󰊻 "
"VirtualBox" = " "
"vlc" = "󱍼 "
"zathura" = " "
"zen" = "󰇧 "
"zoom" = " "

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"

[title_in_class."st-256color"]
"Yazi" = "󰇥 "
"NVIM" = " "
"btop" = "󰻎 "
"htop" = "󰻎 "

# Sometimes windows do not set a class
[title_in_class.""]
"Steam" = " "

[title_in_class."VirtualBox Machine"]
"Tiny11" = " "

[title_in_class."steam"]
"Halo: The Master Chief Collection" = " "

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
aProgram = "^$"
"(?i)TestApp" = ""
"" = "^$"
"[Ss]team" = "^(Friends List.*)?$"
"(?i)fcitx" = ".*"

[format]
dedup = false
dedup_inactive_fullscreen = false
delim = ""
workspace = "{id} {clients}"
workspace_empty = "{id}"
# client = "<span>{icon}</span>"
client = "{icon}"
client_fullscreen = "{icon}"
# client_active = "<span style='color:#FFFFFF'>{icon}</font>"
client_active = "󰀦{icon}"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
